plugins { id 'com.android.application' }

android {
    namespace 'in.vasukinfc.billcalculator'
    compileSdk 35

    defaultConfig {
        applicationId 'in.vasukinfc.billcalculator'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }
}

dependencies {
    implementation 'com.google.zxing:core:3.5.3'
}
